app/protected/models/QuietHour.php
<?php

/**
 * This is the model class for table "{{quiet_hour}}".
 *
 * The followings are the available columns in table '{{quiet_hour}}':
 * @property integer $id
 * @property integer $user_id
 * @property integer $days
 * @property integer $start_interval
 * @property integer $end_interval
 * @property string $created_at
 * @property string $modified_at
 *
 * The followings are the available model relations:
 * @property Users $user
 */
class QuietHour extends CActiveRecord
{
  const DAYS_EVERYDAY = 0;
  const DAYS_WEEKDAYS = 10;
  const DAYS_WEEKENDS = 20;
  const DAYS_MONDAY = 30;
  const DAYS_TUESDAY = 40;
  const DAYS_WEDNESDAY = 50;
  const DAYS_THURSDAY = 60;
  const DAYS_FRIDAY = 70;
  const DAYS_SATURDAY = 80;
  const DAYS_SUNDAY = 90;
  
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return QuietHour the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{quiet_hour}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('modified_at', 'required'),
			array('user_id, days, start_interval, end_interval', 'numerical', 'integerOnly'=>true),
			array('created_at', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, user_id, days, start_interval, end_interval, created_at, modified_at', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'user_id' => 'User',
			'days' => 'Days',
			'start_interval' => 'Start Interval',
			'end_interval' => 'End Interval',
			'created_at' => 'Created At',
			'modified_at' => 'Modified At',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('days',$this->days);
		$criteria->compare('start_interval',$this->start_interval);
		$criteria->compare('end_interval',$this->end_interval);
		$criteria->compare('created_at',$this->created_at,true);
		$criteria->compare('modified_at',$this->modified_at,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function getDaysOptions()
  {
    return array(self::DAYS_EVERYDAY => 'Everyday',self::DAYS_WEEKDAYS => 'Monday through Friday',self::DAYS_WEEKENDS => 'Saturday and Sunday',self::DAYS_MONDAY => 'Monday',self::DAYS_TUESDAY => 'Tuesday',self::DAYS_WEDNESDAY => 'Wednesday',self::DAYS_THURSDAY => 'Thursday',self::DAYS_FRIDAY => 'Friday',self::DAYS_SATURDAY => 'Saturday',self::DAYS_SUNDAY => 'Sunday');
   }		
   
   public function getStartOptions()
   {
      return $this->buildTimeSelectArray();
 	 } 

   public function getEndOptions()
   {
     return $this->buildTimeSelectArray();    
 	 } 
 	 
 	 public function buildTimeSelectArray() {
 	   $ts = array();
 	   $ts[0] = '12:00 am';
 	   $ts[30] = '12:30 am';
 	   $ts[100] = '1:00 am';
 	   $ts[130] = '1:30 am';
 	   $ts[200] = '2:00 am';
 	   $ts[230] = '2:30 am';
 	   $ts[300] = '3:00 am';
 	   $ts[330] = '3:30 am';
 	   $ts[400] = '4:00 am';
 	   $ts[430] = '4:30 am';
 	   $ts[500] = '5:00 am';
 	   $ts[530] = '5:30 am';
 	   $ts[600] = '6:00 am';
 	   $ts[630] = '6:30 am';
 	   $ts[700] = '7:00 am';
 	   $ts[730] = '7:30 am';
 	   $ts[800] = '8:00 am';
 	   $ts[830] = '8:30 am';
 	   $ts[900] = '9:00 am';
 	   $ts[930] = '9:30 am';
 	   $ts[1000] = '10:00 am';
 	   $ts[1030] = '10:30 am';
 	   $ts[1100] = '11:00 am';
 	   $ts[1130] = '11:30 am';
 	   $ts[1200] = '12:00 pm';
 	   $ts[1230] = '12:30 pm';
 	   $ts[1300] = '1:00 pm';
 	   $ts[1330] = '1:30 pm';
 	   $ts[1400] = '2:00 pm';
 	   $ts[1430] = '2:30 pm';
 	   $ts[1500] = '3:00 pm';
 	   $ts[1530] = '3:30 pm';
 	   $ts[1600] = '4:00 pm';
 	   $ts[1630] = '4:30 pm';
 	   $ts[1700] = '5:00 pm';
 	   $ts[1730] = '5:30 pm';
 	   $ts[1800] = '6:00 pm';
 	   $ts[1830] = '6:30 pm';
 	   $ts[1900] = '7:00 pm';
 	   $ts[1930] = '7:30 pm';
 	   $ts[2000] = '8:00 pm';
 	   $ts[2030] = '8:30 pm';
 	   $ts[2100] = '9:00 pm';
 	   $ts[2130] = '9:30 pm';
 	   $ts[2200] = '10:00 pm';
 	   $ts[2230] = '10:30 pm';
 	   $ts[2300] = '11:00 pm';
 	   $ts[2330] = '11:30 pm';
 	   return $ts;
 	 }
 	 
 	 public function debug() {
  		$ui = UserSetting::model()->loadByUser(1);
  		if (!empty($ui) and $ui->timezone<>'')
 	      date_default_timezone_set($ui->timezone); 	   
     $current_day_week = date('w'); // 0 Sunday - 6 Saturday
     $current_time = date('Hi'); // 0000 - 2359
     echo 'Current dow: '.date('w');lb();
     echo 'Current time: '.date('Hi');lb();
 	  $qh = QuietHour::model()->findAll();
 	  foreach ($qh as $q) {
        echo 'Day'.$q->days;lb();
        echo 'Start'.$q->start_interval;lb();
        echo 'End'.$q->end_interval;lb();
        lb();
 	  }
     
 	   
 	 }

}

app/protected/controllers/QuiethourController.php
<?php

class QuiethourController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(''),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','view','create','update','delete','dnd'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new QuietHour;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['QuietHour']))
		{
			$model->attributes=$_POST['QuietHour'];
      $model->user_id = Yii::app()->user->id;
      $model->created_at =new CDbExpression('NOW()'); 
      $model->modified_at =new CDbExpression('NOW()');          
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['QuietHour']))
		{
			$model->attributes=$_POST['QuietHour'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
	  $ui = UserSetting::model()->loadByUser(Yii::app()->user->id);
		$dataProvider=new CActiveDataProvider('QuietHour');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,'ui'=>$ui,
		));
	}
	
	public function actionDnd()
	{
	  $ui = UserSetting::model()->loadByUser(Yii::app()->user->id);
	  if ($ui->do_not_disturb ==0)
	    $dnd = 1;
	  else
	    $dnd =0;
    $update_dnd = Yii::app()->db->createCommand()->update(Yii::app()->getDb()->tablePrefix.'user_setting',array('do_not_disturb'=>$dnd),'user_id=:user_id', array(':user_id'=>Yii::app()->user->id));
		$this->redirect(array('index'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new QuietHour('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['QuietHour']))
			$model->attributes=$_GET['QuietHour'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=QuietHour::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='quiet-hour-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/quiethour/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'quiet-hour-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

  <?php
    echo CHtml::activeLabel($model,'days',array('label'=>'Which day')); 
  ?>
  <?php echo $form->dropDownList($model,'days', $model->getDaysOptions()); ?>

  <?php
    echo CHtml::activeLabel($model,'start_interval',array('label'=>'Start')); 
  ?>
  <?php echo $form->dropDownList($model,'start_interval', $model->getStartOptions()); ?>

  <?php
    echo CHtml::activeLabel($model,'end_interval',array('label'=>'End')); 
  ?>
  <?php echo $form->dropDownList($model,'end_interval', $model->getEndOptions()); ?>

  <p><em>Quiet hours require the advanced module. <a href="/site/page?view=upgrade">Learn more</a>.</em></p>


	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/quiethour/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'user_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'days',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'start_interval',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'end_interval',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'created_at',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'modified_at',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/quiethour/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('days')); ?>:</b>
	<?php echo CHtml::encode($data->days); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('start_interval')); ?>:</b>
	<?php echo CHtml::encode($data->start_interval); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('end_interval')); ?>:</b>
	<?php echo CHtml::encode($data->end_interval); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_at')); ?>:</b>
	<?php echo CHtml::encode($data->created_at); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('modified_at')); ?>:</b>
	<?php echo CHtml::encode($data->modified_at); ?>
	<br />


</div>

app/protected/views/quiethour/admin.php
<?php
$this->breadcrumbs=array(
	'Quiet Hours'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List QuietHour','url'=>array('index')),
	array('label'=>'Create QuietHour','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('quiet-hour-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Quiet Hours</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'quiet-hour-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'user_id',
		'days',
		'start_interval',
		'end_interval',
		'created_at',
		/*
		'modified_at',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

app/protected/views/quiethour/create.php
<?php
$this->breadcrumbs=array(
	'Quiet Hours'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Intervals','url'=>array('index')),
);
?>

<h1>Add a Quiet Hour Interval</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

app/protected/views/quiethour/index.php
<?php
$this->breadcrumbs=array(
	'Quiet Hours',
);

if ($ui->do_not_disturb==0) {
  $this->menu=array(
  	array('label'=>'Add an interval','url'=>array('create')),
  	array('label'=>'Turn Do Not Disturb ON','url'=>array('dnd')),
  );  
} else {
  $this->menu=array(
  	array('label'=>'Add an interval','url'=>array('create')),
  	array('label'=>'Turn Do Not Disturb OFF','url'=>array('dnd')),
  );    
}

?>

<h1>Quiet Hours</h1>

<?php
  if (Yii::app()->params['version']=='basic') {
      Yii::app()->user->setFlash('upgrade', '<p><em>The Quiet Hours feature requires the advanced module to operate. <a href="/site/page?view=upgrade">Learn more</a>.</em></p>');
      $this->widget('bootstrap.widgets.TbAlert', array(
          'alerts'=>array( // configurations per alert type
      	    'upgrade'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), 
          ),
      ));
    }
?>

<?php
  $cntrlr = Yii::app()->controller->action->id; 
      $gridColumns = array(      
      	  array('class'=>'CDataColumn','value'=> 'getQuietHourDay($data->days)', 'header'=>'Days'),
          'start_interval',
          'end_interval',
      	        array(
          'htmlOptions'=>array('width'=>'100px'),  		
        	'class'=>'bootstrap.widgets.TbButtonColumn',
        	'header'=>'Options',
          'template'=>'{update}{delete}',
              'buttons'=>array
              (
            'update' => array
            (
              'options'=>array('title'=>'Update properties'),
              'label'=>'<i class="icon-pencil icon-large" style="margin:5px;"></i>',
              'url'=>'Yii::app()->createUrl("quiethour/update", array("id"=>$data->id))',
            ),
                  'delete' => array
                  (
                  'options'=>array('title'=>'trash'),
                    'label'=>'<i class="icon-trash icon-large" style="margin:5px;"></i>',
                    'url'=>'Yii::app()->createUrl("quiethour/delete", array("id"=>$data->id))',
                  ),
              ),			
        ),

      );
    
 $this->widget('bootstrap.widgets.TbGridView', array(
	'type'=>'striped',
		'hideHeader'=>false,
	'dataProvider'=>$dataProvider,
	'template'=>"{items}\n{pager}",
	'columns'=>$gridColumns,
));

?>

app/protected/views/quiethour/update.php
<?php
$this->breadcrumbs=array(
	'Quiet Hours'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List intervals','url'=>array('index')),
	array('label'=>'Add interval','url'=>array('create')),
);
?>

<h1>Update QuietHour Interval</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

app/protected/views/quiethour/view.php
<?php
$this->breadcrumbs=array(
	'Quiet Hours'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List QuietHour','url'=>array('index')),
	array('label'=>'Create QuietHour','url'=>array('create')),
	array('label'=>'Update QuietHour','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete QuietHour','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage QuietHour','url'=>array('admin')),
);
?>

<h1>View QuietHour #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'user_id',
		'days',
		'start_interval',
		'end_interval',
		'created_at',
		'modified_at',
	),
)); ?>