app/protected/models/AlertKeyword.php
<?php

/**
 * This is the model class for table "{{alert_keyword}}".
 *
 * The followings are the available columns in table '{{alert_keyword}}':
 * @property integer $id
 * @property integer $user_id
 * @property string $keyword
 * @property string $created_at
 * @property string $modified_at
 */
class AlertKeyword extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return AlertKeyword the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{alert_keyword}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('keyword, modified_at', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('keyword', 'length', 'max'=>255),
			array('created_at', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, user_id, keyword, created_at, modified_at', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'user_id' => 'User',
			'keyword' => 'Keyword',
			'created_at' => 'Created At',
			'modified_at' => 'Modified At',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('keyword',$this->keyword,true);
		$criteria->compare('created_at',$this->created_at,true);
		$criteria->compare('modified_at',$this->modified_at,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	public function scan($msg) {
	  // scans subject line and email address for each keyword
	  $kws = AlertKeyword::model()->findAll();
	  $email = $msg['personal'].' '.$msg['mailbox'].$msg['host'];
	  foreach ($kws as $k) {
	    if (stristr($msg['subject'],$k->keyword)!==false
	      or stristr($email,$k->keyword)!==false) {
	      return true;	      
	    }
	  }
	  return false;
	}
	
	// scoping functions
	
  public function owned_by($user_id = 0)
  {
    $this->getDbCriteria()->mergeWith( array(
      'condition'=>'user_id='.$user_id,
    ));
      return $this;
  }
	
}

app/protected/controllers/AlertkeywordController.php
<?php

class AlertkeywordController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(''),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','view','create','update','delete'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new AlertKeyword;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['AlertKeyword']))
		{
			$model->attributes=$_POST['AlertKeyword'];
			$model->keyword = strtolower($model->keyword);
      $model->user_id = Yii::app()->user->id;
      $model->created_at =new CDbExpression('NOW()'); 
      $model->modified_at =new CDbExpression('NOW()');          			  
			if($model->save()) {
				$this->redirect(array('index'));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['AlertKeyword']))
		{
			$model->attributes=$_POST['AlertKeyword'];
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('AlertKeyword',
		array(
        'criteria'=>array(
            'condition'=>'user_id='.Yii::app()->user->id,
            'order'=>'keyword ASC',
        ),)
		);
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new AlertKeyword('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['AlertKeyword']))
			$model->attributes=$_GET['AlertKeyword'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=AlertKeyword::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='alert-keyword-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/alertkeyword/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'alert-keyword-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'keyword',array('class'=>'span5','maxlength'=>255)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/alertkeyword/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'user_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'keyword',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'created_at',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'modified_at',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/alertkeyword/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('keyword')); ?>:</b>
	<?php echo CHtml::encode($data->keyword); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_at')); ?>:</b>
	<?php echo CHtml::encode($data->created_at); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('modified_at')); ?>:</b>
	<?php echo CHtml::encode($data->modified_at); ?>
	<br />


</div>

app/protected/views/alertkeyword/admin.php
<?php
$this->breadcrumbs=array(
	'Alert Keywords'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List AlertKeyword','url'=>array('index')),
	array('label'=>'Create AlertKeyword','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('alert-keyword-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Alert Keywords</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'alert-keyword-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'user_id',
		'keyword',
		'created_at',
		'modified_at',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

app/protected/views/alertkeyword/create.php
<?php
$this->breadcrumbs=array(
	'Alert Keywords'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Keywords','url'=>array('index')),
);
?>

<h1>Add a Keyword</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

app/protected/views/alertkeyword/index.php
<?php
$this->breadcrumbs=array(
	'Alert Keywords',
);

$this->menu=array(
	array('label'=>'Add a Keyword','url'=>array('create')),
);
?>

<h1>Alert Keywords</h1>
<?php
  if (Yii::app()->params['version']=='basic') {
      Yii::app()->user->setFlash('upgrade', '<p><em>This feature requires the advanced module and the Pushover smartphone application for processing alerts. <a href="/site/page?view=upgrade">Learn more</a>.</em></p>');
      $this->widget('bootstrap.widgets.TbAlert', array(
          'alerts'=>array( // configurations per alert type
      	    'upgrade'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), 
          ),
      ));
    }
?>

<p>You will receive smartphone notifications via Pushover when email is received whose subject or email address fields contain any of the following keywords. You can also configure alerts per sender by <a href="/sender/index">updating individual senders</a>.</p><p>To properly receive notifications, configure your <a href="/usersetting/update">Pushover settings</a> and ensure that your Pushover application token is included in Filtered.ini.</p>


<?php
$cntrlr = Yii::app()->controller->action->id; 
      $gridColumns = array(   
        'keyword',
      	array(
          'htmlOptions'=>array('width'=>'100px'),  		
        	'class'=>'bootstrap.widgets.TbButtonColumn',
        	'header'=>'Options',
          'template'=>'{update}{delete}',
              'buttons'=>array
              (
                  'update' => array
                  (
                    'options'=>array('title'=>'Update keyword'),
                    'label'=>'<i class="icon-pencil icon-large" style="margin:5px;"></i>',
                    'url'=>'Yii::app()->createUrl("alertkeyword/update", array("id"=>$data->id))',
                  ),
              
                  'delete' => array
                  (
                  'options'=>array('title'=>'trash'),
                    'label'=>'<i class="icon-trash icon-large" style="margin:5px;"></i>',
                    'url'=>'Yii::app()->createUrl("alertkeyword/delete", array("id"=>$data->id))',
                  ),
              ),			
        ),

      );
    
 $this->widget('bootstrap.widgets.TbGridView', array(
	'type'=>'striped',
		'hideHeader'=>false,
	'dataProvider'=>$dataProvider,
	'template'=>"{items}\n{pager}",
	'columns'=>$gridColumns,
));

?>

app/protected/views/alertkeyword/update.php
<?php
$this->breadcrumbs=array(
	'Alert Keywords'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List AlertKeyword','url'=>array('index')),
	array('label'=>'Create AlertKeyword','url'=>array('create')),
	array('label'=>'View AlertKeyword','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage AlertKeyword','url'=>array('admin')),
);
?>

<h1>Update AlertKeyword <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

app/protected/views/alertkeyword/view.php
<?php
$this->breadcrumbs=array(
	'Alert Keywords'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List AlertKeyword','url'=>array('index')),
	array('label'=>'Create AlertKeyword','url'=>array('create')),
	array('label'=>'Update AlertKeyword','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete AlertKeyword','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage AlertKeyword','url'=>array('admin')),
);
?>

<h1>View AlertKeyword #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'user_id',
		'keyword',
		'created_at',
		'modified_at',
	),
)); ?>