app/protected/models/Folder.php
<?php

/**
 * This is the model class for table "{{folder}}".
 *
 * The followings are the available columns in table '{{folder}}':
 * @property integer $id
 * @property integer $account_id
 * @property integer $user_id
 * @property string $name
 * @property integer $train
 * @property integer $digest
 * @property string $created_at
 * @property string $modified_at
 *
 * The followings are the available model relations:
 * @property Users $user
 * @property Account $account
 */
class Folder extends CActiveRecord
{
  public $account_name;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Folder the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{folder}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, modified_at', 'required'),
			array('account_id, user_id, train, digest', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('created_at', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, account_id, user_id, name, train, digest, created_at, modified_at, account_name', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'account' => array(self::BELONGS_TO, 'Account', 'account_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'account_id' => 'Account',
			'user_id' => 'User',
			'name' => 'Name',
			'train' => 'Train',
			'digest' => 'Digest',
			'created_at' => 'Created At',
			'modified_at' => 'Modified At',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
		$account_table = Account::model()->tableName();
    $account_name_sql = "(select name from $account_table acct where acct.id = t.account_id)";
    $criteria->select = array(
            '*',
            $account_name_sql . " as account_name",
        );    
		$criteria->compare('id',$this->id);
		$criteria->compare('account_id',$this->account_id);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('train',$this->train);
		$criteria->compare('digest',$this->digest);
		$criteria->compare('created_at',$this->created_at,true);
		$criteria->compare('modified_at',$this->modified_at,true);
    $criteria->compare($account_name_sql, $this->account_name);		

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
      'pagination' => array(
                  'pageSize' => Yii::app()->params['postsPerPage'],
             ),
       'sort' => array(
         'defaultOrder' => 'account_name asc, t.name asc',
                         'attributes' => array(
                             // order by
                             'account_name' => array(
                                 'asc' => 'account_name ASC',
                                 'desc' => 'account_name DESC',
                             ),
                             '*',
                         ),
                     ),        
		));
	}
	
	public function getNamewithaccount()
  {
    return $this->name.' ('.$this->account->name.')';
  }
		
	public function lookup($account_id,$name) {
	  // lookup folder by account and name
    $f = Folder::model()->findByAttributes(array('account_id'=>$account_id,'name'=>$name));
	  if (empty($f)) {
	    return 0;
	  }	else {
	    return $f['id'];
	  }	  
	}
	
  public function add($user_id,$account_id,$name,$train) {
    $f = Folder::model()->findByAttributes(array('user_id'=>$user_id,'account_id'=>$account_id,'name'=>$name));
	  if (empty($f)) {
	    $folder = new Folder;
	    $folder->user_id = $user_id;
	    $folder->account_id = $account_id;
	    $folder->name = $name;
	    $folder->train = $train;
	    $folder->digest = 1;
      $folder->created_at =new CDbExpression('NOW()'); 
      $folder->modified_at =new CDbExpression('NOW()');          
      $folder->save();
	    $folder_id = $folder->id;
	  } else {
	    $folder_id = $f['id'];
	  }
	  return $folder_id;
  }
	
  public function initialize($account_id) {
    // create the default filtering mailboxes in remote account
    $r = new Remote();
    $account = Account::model()->findByPk($account_id);
    $user_id = $account->user_id;
    $provider = $account->provider;
    $this->add($user_id,$account_id,'Inbox',1);
    if ($provider == Account::PROVIDER_FASTMAIL) {
      // These are the folders we train by default
      $this->add($user_id,$account_id,'Inbox.+Filtering.Bulk',1);
      $this->add($user_id,$account_id,'Inbox.+Filtering.Zap',1);    
      $folders = array('Inbox.+Filtering','Inbox.+Filtering.Bulk','Inbox.+Filtering.Review','Inbox.+Filtering.Zap');      
    } else if ($provider == Account::PROVIDER_GMAIL) {
      $this->add($user_id,$account_id,'+Filtering/Bulk',1);
      $this->add($user_id,$account_id,'+Filtering/Zap',1);    
      $folders = array('+Filtering','+Filtering/Bulk','+Filtering/Review','+Filtering/Zap');
    } else if ($provider == Account::PROVIDER_DOVECOT) {
          $this->add($user_id,$account_id,'INBOX/+Filtering/Bulk',1);
          $this->add($user_id,$account_id,'INBOX/+Filtering/Zap',1);
          $folders = array('INBOX/+Filtering','INBOX/+Filtering/Bulk','INBOX/+Filtering/Review','INBOX/+Filtering/Zap');
    } else {
          $this->add($user_id,$account_id,'+Filtering/Bulk',1);
          $this->add($user_id,$account_id,'+Filtering/Zap',1);
          $folders = array('+Filtering','+Filtering/Bulk','+Filtering/Review','+Filtering/Zap');
    }
    // create the folders remotely in the mailbox    
    foreach ($folders as $f) {
      // create remote imap folder
      $r->createMailbox($account_id,$f);
    }
  }

  public function initialize_private($user_id,$account_id) {
    // initialize private folder
    $r = new Remote();
    $r->setDefaultPaths($account_id);
    $this->add($user_id,$account_id,$r->path_private,1);
    $r->createMailbox($account_id,$r->path_private);
  }
  
  public function train($id) {
    // train folder based on existing contents
    $r=new Remote();
    $results = $r->trainFolder($id);
    return $results;
  }
 
  public function createRemote($account_id,$name) {
    // create the default filtering mailboxes in remote account
    $r = new Remote();
    $account = Account::model()->findByPk($account_id);
    $user_id = $account->user_id;
    $provider = $account->provider;
    if ($provider == Account::PROVIDER_FASTMAIL) {
      if (strtolower(substr($name,0,6))<>'inbox.')
        $name = 'Inbox.'.$name;
    } else if ($provider == Account::PROVIDER_GMAIL) {
      // no changes
    }
    $result = $r->createMailbox($account_id,$name);
    return $result;
  }
  
  public function renameRemote($account_id,$current_name,$new_name) {
    $r = new Remote();
    $result = $r->renameMailbox($account_id,$current_name,$new_name);
    return $result;
  }
  // scoping functions
  public function owned_by($user_id = 0)
  {
    $this->getDbCriteria()->mergeWith( array(
      'condition'=>'user_id='.$user_id,
    ));
      return $this;
  }
  
	
}

app/protected/controllers/FolderController.php
<?php

class FolderController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(''),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','index','view','delete','train'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Folder;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
    // defaults
    $model->train =1;
    $model->digest =1;
		if(isset($_POST['Folder']))
		{		  
			$model->attributes=$_POST['Folder'];
      $model->user_id = Yii::app()->user->id;
      $model->created_at =new CDbExpression('NOW()'); 
      $model->modified_at =new CDbExpression('NOW()');          
			if($model->save()) {
			  $model->createRemote($model->account_id,$model->name);
				$this->redirect(array('index'));			  
			}
		} 

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
    $current_name = $model->name;
		if(isset($_POST['Folder']))
		{
			$model->attributes=$_POST['Folder'];
			if ($model->validate()) {
			  if ($current_name <> $model->name) {
			    $result = $model->renameRemote($model->account_id,$current_name,$model->name);
			  }
  			if($model->save()) {
  				$this->redirect(array('index'));
  			}			  
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
    		$model=new Folder('search');
    		$model->unsetAttributes();  // clear any default values
    		$model->user_id = Yii::app()->user->id;
    		if(isset($_GET['Folder']))
    			$model->attributes=$_GET['Folder'];
    		$this->render('index',array(
    			'model'=>$model->owned_by(Yii::app()->user->id),
    		));     		
	}

	public function actionTrain($id)
	{
		$model=$this->loadModel($id);
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
			    $result = $model->train($id);
      		$this->render('train',array(
      			'model'=>$model,'train'=>$result,
      		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Folder('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Folder']))
			$model->attributes=$_GET['Folder'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Folder::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='folder-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/folder/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'folder-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

  <?php
  echo CHtml::activeLabel($model,'train',array('label'=>'Include this folder in training?')); 
   echo $form->dropDownList($model,'train', array('0' => 'No','1' => 'Yes')); ?>
  <?php
  echo CHtml::activeLabel($model,'digest',array('label'=>'Include this folder in digest summaries?')); 
  
   echo $form->dropDownList($model,'digest', array('0' => 'No','1' => 'Yes')); ?>


	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/folder/_new.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'folder-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

  <?php 
      echo CHtml::activeLabel($model,'account_id',array('label'=>'Choose a mail account:')); 
      echo CHtml::activeDropDownList($model,'account_id',Account::model()->getAccountList(),array('empty'=>'Select an Account'));
      
  ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

  <?php
  echo CHtml::activeLabel($model,'train',array('label'=>'Include this folder in training?')); 
   echo $form->dropDownList($model,'train', array('1' => 'Yes', '0' => 'No')); ?>
  <?php
  echo CHtml::activeLabel($model,'digest',array('label'=>'Include this folder in digest summaries?')); 
  
   echo $form->dropDownList($model,'digest', array('1' => 'Yes', '0' => 'No')); ?>


	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/folder/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'account_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'user_id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'train',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'digest',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'created_at',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'modified_at',array('class'=>'span5')); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/folder/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('account_id')); ?>:</b>
	<?php echo CHtml::encode($data->account_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('train')); ?>:</b>
	<?php echo CHtml::encode($data->train); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('digest')); ?>:</b>
	<?php echo CHtml::encode($data->digest); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_at')); ?>:</b>
	<?php echo CHtml::encode($data->created_at); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('modified_at')); ?>:</b>
	<?php echo CHtml::encode($data->modified_at); ?>
	<br />

	*/ ?>

</div>

app/protected/views/folder/admin.php
<?php
$this->breadcrumbs=array(
	'Folders'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Folder','url'=>array('index')),
	array('label'=>'Create Folder','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('folder-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Folders</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'folder-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'account_id',
		'user_id',
		'name',
		'train',
		'digest',
		/*
		'created_at',
		'modified_at',
		*/
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

app/protected/views/folder/create.php
<?php
$this->breadcrumbs=array(
	'Folders'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Folder','url'=>array('index')),
	array('label'=>'Manage Folder','url'=>array('admin')),
);
?>

<h1>Create Folder</h1>

<?php echo $this->renderPartial('_new', array('model'=>$model)); ?>

app/protected/views/folder/index.php
<?php
$this->breadcrumbs=array(
	'Folders',
);

$this->menu=array(
	array('label'=>'Create Folder','url'=>array('create')),
);
?>

<h1>Folders</h1>

<?php

/*  $cntrlr = Yii::app()->controller->action->id; 
      $gridColumns = array(      
      	array('class'=>'CLinkColumn','labelExpression'=>'$data->name', 'header'=>'Name','urlExpression'=>'Yii::app()->baseUrl."/folder/update/$data->id"'),
      	array('class'=>'CLinkColumn','labelExpression'=>'$data->account->name', 'header'=>'Account','urlExpression'=>'Yii::app()->baseUrl."/folder/update/$data->id"'),
     array(            
            'name'=>'account_name',
            'header'=>'Account',
            'filter'=>CHtml::listData(Account::model()->findAll(),'name','name'),
            'value'=>'$data->account_name',
        ),
      	        array(
          'htmlOptions'=>array('width'=>'100px'),  		
        	'class'=>'bootstrap.widgets.TbButtonColumn',
        	'header'=>'Options',
          'template'=>'{update}{delete}',
              'buttons'=>array
              (
            'update' => array
            (
              'options'=>array('title'=>'Update properties'),
              'label'=>'<i class="icon-pencil icon-large" style="margin:5px;"></i>',
              'url'=>'Yii::app()->createUrl("folder/update", array("id"=>$data->id))',
            ),
                  'delete' => array
                  (
                  'options'=>array('title'=>'trash'),
                    'label'=>'<i class="icon-trash icon-large" style="margin:5px;"></i>',
                    'url'=>'Yii::app()->createUrl("folder/delete", array("id"=>$data->id))',
                  ),
              ),			
        ),

      );
    
 $this->widget('bootstrap.widgets.TbGridView', array(
	'type'=>'striped',
		'hideHeader'=>false,
	'dataProvider'=>$model,
	'filter'=>$model,	
	'template'=>"{items}\n{pager}",
	'columns'=>$gridColumns,
));

*/

 $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'folder-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(      
	  'name',
    array(            
        'name'=>'account_name',
        'header'=>'Account',
  'filter'=>CHtml::dropDownList(
                                  'Folder[account_name]',
                                  $model->account_name,
                                  CHtml::listData(
                                          Account::model()->findAll(),
                                          'name',
                                          'name'),array('empty' => 'All')),
        'value'=>'$data->account_name',
    ),
  	  array(
      	'class'=>'bootstrap.widgets.TbButtonColumn',
      'htmlOptions'=>array('width'=>'100px'),  		
    	'header'=>'Options',
      'template'=>'{update} {train} {delete}',
      'buttons'=>array
      (
        'train' => array
        (
          'options'=>array('title'=>'Train folder'),
          'label'=>'<i class="icon-filter icon-large" ></i>',
          'url'=>'Yii::app()->createUrl("folder/train", array("id"=>$data->id))',
        ),
      ),
    ),
  ),
)); ?>

app/protected/views/folder/train.php
<?php
$this->breadcrumbs=array(
	'Folders',
);

$this->menu=array(
	array('label'=>'List Folders','url'=>array('index')),
	array('label'=>'Create Folder','url'=>array('create')),
);
?>

<h1>Results of Training Folder: <?php echo $model->name; ?></h1>
<p>The following senders were found in this folder and set to route here in the future:<br /> <em>(currently we look one year or 250 messages back in the folder but you can customize this in Remote->trainFolder)</em></p>
<?php
  if (!empty($train)) {
    foreach ($train as $t) {
      echo '<p>'.$t.'</p>';
    }    
  } else {
    echo 'Sorry, no senders were found in this folder.';lb();
  }

?>

app/protected/views/folder/update.php
<?php
$this->breadcrumbs=array(
	'Folders'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Folders','url'=>array('index')),
	array('label'=>'Create Folder','url'=>array('create')),
);
?>

<h1>Update <?php echo $model->name; ?> Folder</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

app/protected/views/folder/view.php
<?php
$this->breadcrumbs=array(
	'Folders'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Folder','url'=>array('index')),
	array('label'=>'Create Folder','url'=>array('create')),
	array('label'=>'Update Folder','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete Folder','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Folder','url'=>array('admin')),
);
?>

<h1>View Folder #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'account_id',
		'user_id',
		'name',
		'train',
		'digest',
		'created_at',
		'modified_at',
	),
)); ?>