app/protected/controllers/SenderController.php
<?php

class SenderController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('verify','program'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('recent','index','trained','view','create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Sender;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Sender']))
		{
			$model->attributes=$_POST['Sender'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
    $last_folder_id = $model->folder_id;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		if(isset($_POST['Sender']))
		{
			$model->attributes=$_POST['Sender'];
			$model->last_folder_id = $last_folder_id;
			$model->last_trained = time();
			if($model->save()) {
			  $r = new Remote;
			  $r->scanForSender($model,false);
		    Yii::app()->user->setFlash('updated','Your settings have been saved.');
				$this->redirect(array('update','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,'message_count'=>count($model->messages)
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
	  $this->layout = '//layouts/column1';
	  $model=new Sender('search');  		  	
	  if(isset($_POST['sender-grid_c0']) and !empty($_POST['Sender']['folder_id']))
	  {
	    $dest_folder_id = $_POST['Sender']['folder_id'];
	    $sender_list = $_POST['sender-grid_c0'];
	    foreach ($sender_list as $sender_id) {
	      // train sender to folder_id
	      $model->setFolderCheckAccount($sender_id,$dest_folder_id);
	    }
	    Yii::app()->user->setFlash('trained','Your selections have been trained. <em><strong>Note:</strong> Trainings set to folders in the wrong account will be ignored.</em>');
	    unset($_POST['Sender']['folder_id']);
		} 
  		$model->unsetAttributes();  // clear any default values
  		$model->user_id = Yii::app()->user->id;      		
  		$model->folder_id = 0;
  		if(isset($_GET['Sender']))
  			$model->attributes=$_GET['Sender'];
  		else if(isset($_POST['Sender']))
  			$model->attributes=$_POST['Sender'];
  		$this->render('index',array(
  			'model'=>$model->owned_by(Yii::app()->user->id),
  		));
	}
	
	public function actionRecent()
	{
	  $this->layout = '//layouts/column1';
  		$model=new Sender('search');  		
	  
	  if(isset($_POST['sender-grid_c0']) and !empty($_POST['Sender']['folder_id']))
	  {
	    $dest_folder_id = $_POST['Sender']['folder_id'];
	    $sender_list = $_POST['sender-grid_c0'];
	    foreach ($sender_list as $sender_id) {
	      // train sender to folder_id
	      $model->setFolderCheckAccount($sender_id,$dest_folder_id);
	    }
	    Yii::app()->user->setFlash('trained','Your selections have been trained. <em><strong>Note:</strong> Trainings set to folders in the wrong account will be ignored.</em>');		   
	    unset($_POST['Sender']['folder_id']);	     	    
		}  		
  		$model->unsetAttributes();  // clear any default values
  		$model->user_id = Yii::app()->user->id;      		
  		if(isset($_GET['Sender']))
  			$model->attributes=$_GET['Sender'];
  		else if(isset($_POST['Sender']))
  			$model->attributes=$_POST['Sender'];
  		$this->render('recent',array(
  			'model'=>$model,
  		));
	}

	public function actionTrained()
	{
	  $this->layout = '//layouts/column1';
	  	$model=new Sender('search');  		
  	
	  if(isset($_POST['sender-grid_c0']) and !empty($_POST['Sender']['folder_id']))
	  {
	    $dest_folder_id = $_POST['Sender']['folder_id'];
	    $sender_list = $_POST['sender-grid_c0'];
	    foreach ($sender_list as $sender_id) {
	      // train sender to folder_id
	      $model->setFolderCheckAccount($sender_id,$dest_folder_id);
	    }
	    Yii::app()->user->setFlash('trained','Your selections have been trained. <em><strong>Note:</strong> Trainings set to folders in the wrong account will be ignored.</em>');		 
	    unset($_POST['Sender']['folder_id']);
	    
		}  		
  		$model->unsetAttributes();  // clear any default values
  		$model->user_id = Yii::app()->user->id;      		
  		if(isset($_GET['Sender']))
  			$model->attributes=$_GET['Sender'];
  		else if(isset($_POST['Sender']))
  			$model->attributes=$_POST['Sender'];
  		$this->render('trained',array(
  			'model'=>$model,
  		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Sender('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Sender']))
			$model->attributes=$_GET['Sender'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

  public function actionVerify($s = 0, $m=0,$u=0) {
    // verify that secure msg url from digest is valid, log in user, show msg
    $sender_id = $s;
    $message_id = $m;
    $udate = $u;
    $msg = Message::model()->findByPk($message_id);
    if (!empty($msg) && $msg->sender_id == $sender_id && $msg->udate == $udate) {
      $result = 'Thank you for your assistance. I\'ll respond to your email as soon as possible.';
      $a = new Advanced();
      $a->verifySender($msg->account_id,$sender_id);
    } else {
      $result = 'Sorry, we could not verify your email address.';
    }
		$this->render('verify',array(
			'result'=>$result,
		));
  }

  public function actionProgram($f ='', $s = 0, $m=0,$u=0) {
    // program sender to folder_id if valid message link
    $folder_name = $f;
    $sender_id = $s;
    $message_id = $m;
    $udate = $u;
    // verify link properties from digest
    $msg = Message::model()->findByPk($message_id);
    if (!empty($msg) && $msg->sender_id == $sender_id && $msg->udate == $udate) {
      $r = new Remote();
      $r->setDefaultPaths($msg['account_id']);
      $fld = new Folder();
      if ($folder_name =='inbox') {
        $folder_path = $r->path_inbox;
      } else if ($folder_name =='bulk') {
        $folder_path = $r->path_bulk;
      } else if ($folder_name =='block') {
        $folder_path = $r->path_block;        
      }
      $folder_id = $fld->lookup($msg['account_id'],$folder_path);
      if ($folder_id>0) {
        $sm = new Sender();
        $sm->setFolder($sender_id,$folder_id);        
        $result = 'Sender updated. Thank you.';
      } else {
        $result = 'Sorry, invalid destination folder.';
      }
    } else {
      $result = 'Sorry, we could not verify your credentials.';
    }
		$this->render('program',array(
			'result'=>$result,
		));
  }


	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Sender::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='sender-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/sender/_form.php
<?php 
  if($message_count>0) {
  Yii::app()->user->setFlash('message_count','If you change the destination folder for this Sender, be patient after hitting save. It may take up to a minute to move the messages to the new folder once you click save.');	    
  $this->widget('bootstrap.widgets.TbAlert', array(
      'alerts'=>array( // configurations per alert type
  	    'message_count'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), 
      ),
  ));
}
?>

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'sender-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>
  <?php echo CHtml::activeLabel($model,'account_id',array('label'=>'Account: '.$model->account->name)); ?>

	<?php echo $form->textFieldRow($model,'personal',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'email',array('class'=>'span5','maxlength'=>255)); ?>

  <?php 
      echo CHtml::activeLabel($model,'folder_id',array('label'=>'Choose a Destination Folder:')); 
      echo CHtml::activeDropDownList($model,'folder_id',Sender::model()->getFolderOptions($model->account_id),array('empty'=>'Select a Folder'));
      
  ?>

  <h4>Advanced Features</h4>
  <p><em>The settings below require the advanced module. <a href="/site/page?view=upgrade">Learn more</a>.</em></p>

  <?php
    echo CHtml::activeLabel($model,'exclude_quiet_hours',array('label'=>'Quiet Hours')); 
  ?>
  <?php echo $form->dropDownList($model,'exclude_quiet_hours', $model->getExcludeQuietHoursOptions()); ?>

  <?php
    echo CHtml::activeLabel($model,'alert',array('label'=>'Smartphone Alerts')); 
  ?>
  <?php echo $form->dropDownList($model,'alert', $model->getAlertOptions()); ?>

  <?php
    echo CHtml::activeLabel($model,'expire',array('label'=>'Automated Expiration')); 
  ?>
  <?php echo $form->dropDownList($model,'expire', $model->getExpireOptions()); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>
	<?php
	  if (count($model->messages)>0) {
    	echo '<h4>Recent Messages from this Sender</h4>';
    	foreach ($model->messages as $m) {
    	    if ($m->account_id == $model->account_id)
    	      echo $m->subject;lb();
    	}
	    
	  }
	
	?>

<?php $this->endWidget(); ?>

app/protected/views/sender/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'personal',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->textFieldRow($model,'email',array('class'=>'span5','maxlength'=>255)); ?>


	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

app/protected/views/sender/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('account_id')); ?>:</b>
	<?php echo CHtml::encode($data->account_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('personal')); ?>:</b>
	<?php echo CHtml::encode($data->personal); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mailbox')); ?>:</b>
	<?php echo CHtml::encode($data->mailbox); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('host')); ?>:</b>
	<?php echo CHtml::encode($data->host); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('is_verified')); ?>:</b>
	<?php echo CHtml::encode($data->is_verified); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('folder_id')); ?>:</b>
	<?php echo CHtml::encode($data->folder_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_trained')); ?>:</b>
	<?php echo CHtml::encode($data->last_trained); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_at')); ?>:</b>
	<?php echo CHtml::encode($data->created_at); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('modified_at')); ?>:</b>
	<?php echo CHtml::encode($data->modified_at); ?>
	<br />

	*/ ?>

</div>

app/protected/views/sender/index.php
<?php
$this->breadcrumbs=array(
	'Senders',
);
$this->menu=array(
//	array('label'=>'Create Sender','url'=>array('create')),
 array('label'=>'Manage Sender','url'=>array('admin')),
);
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('sender-grid', {
		data: $(this).serialize()
	});
	return false;
});
");

?>
<h1>Senders</h1>
<?php 

if (Yii::app()->user->hasFlash('trained')) {
  $this->widget('bootstrap.widgets.TbAlert', array(
      'block'=>true, // display a larger alert block?
      'fade'=>true, // use transitions?
      'closeText'=>'×', // close link text - if set to false, no close link is displayed
      'alerts'=>array( // configurations per alert type
  	    'trained'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), // success, info, warning, error or danger
      ),
  ));
  
}

?>

<div>
  <div class="right">
  </div>
<div class="left">
<?php
$this->widget('bootstrap.widgets.TbButtonGroup', array(
  'type' => 'success',
      'toggle' => 'radio',
          'buttons'=>array(
              array('label'=>'Untrained', 'url'=>Yii::app()->getBaseUrl(true).'/sender/index', 'htmlOptions'=> array('class'=>'active')),
              array('label'=>'Trained', 'url'=>Yii::app()->getBaseUrl(true).'/sender/trained'),
              array('label'=>'Recent', 'url'=>Yii::app()->getBaseUrl(true).'/sender/recent'),            
    ),
));
?>
</div>
<br />
</div>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'sender-form',
	'enableAjaxValidation'=>false,
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'sender-grid',
	'dataProvider'=>$model->untrained()->search('message_count desc'),
	'filter'=>$model,
	'columns'=>array(
    array('class'=>'CCheckBoxColumn','selectableRows'=>2),
    array(            
                'name'=>'account_name',
                'header'=>'Account',
                'filter'=>CHtml::dropDownList(
                                                'Sender[account_name]',
                                                $model->account_name,
                                                CHtml::listData(
                                                        Account::model()->findAll(),
                                                        'name',
                                                        'name'),array('empty' => 'All')),                
                'value'=>'$data->account_name',
            ),
		'personal',
		'email',
  	array('class'=>'CDataColumn','name'=> 'message_count', 'header'=>'# Msgs','htmlOptions'=>array('width'=>'25px')),
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
    	'header'=>'Options',
      'template'=>'{update}{delete}',
		),
	),
)); ?>

<div class="form-actions">

<?php 
    echo CHtml::activeLabel($model,'folder_id',array('label'=>'Train to Folder:')); 
    echo CHtml::activeDropDownList($model,'folder_id',Sender::model()->getFolderOptions(),array('empty'=>'Select a Folder'));
    echo '<br />';
   $this->widget('bootstrap.widgets.TbButton', array(
	'buttonType'=>'submit',
	'type'=>'primary',
	'label'=>'Save',
)); ?>

</div>
<?php $this->endWidget(); ?>

<?php
/*  $cntrlr = Yii::app()->controller->action->id; 
      $gridColumns = array(   
array('class'=>'CLinkColumn','labelExpression'=>'getFriendlyEmail($data->personal,$data->email)', 'header'=>'Personal','urlExpression'=>'Yii::app()->baseUrl."/sender/update/$data->id"','htmlOptions'=>array('width'=>'400px')),
      	array('class'=>'CLinkColumn','labelExpression'=>'$data->account->name', 'header'=>'Account','urlExpression'=>'Yii::app()->baseUrl."/sender/update/$data->id"'),

      	        array(
          'htmlOptions'=>array('width'=>'100px'),  		
        	'class'=>'bootstrap.widgets.TbButtonColumn',
        	'header'=>'Options',
          'template'=>'{update}{delete}',
              'buttons'=>array
              (
                  'update' => array
                  (
                    'options'=>array('title'=>'Update properties'),
                    'label'=>'<i class="icon-pencil icon-large" style="margin:5px;"></i>',
                    'url'=>'Yii::app()->createUrl("sender/update", array("id"=>$data->id))',
                  ),
              
                  'delete' => array
                  (
                  'options'=>array('title'=>'trash'),
                    'label'=>'<i class="icon-trash icon-large" style="margin:5px;"></i>',
                    'url'=>'Yii::app()->createUrl("sender/delete", array("id"=>$data->id))',
                  ),
              ),			
        ),

      );
    
 $this->widget('bootstrap.widgets.TbGridView', array(
	'type'=>'striped',
		'hideHeader'=>false,
	'dataProvider'=>$dataProvider,
	'template'=>"{items}\n{pager}",
	'columns'=>$gridColumns,
));
*/
?>

app/protected/views/sender/program.php
<div class="row">
  <div class="span12">
    <?php echo $result; ?>
    </div>
</div>

app/protected/views/sender/recent.php
<?php
$this->breadcrumbs=array(
	'Senders',
);
$this->menu=array(
//	array('label'=>'Create Sender','url'=>array('create')),
 array('label'=>'Manage Sender','url'=>array('admin')),
);
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('sender-grid', {
		data: $(this).serialize()
	});
	return false;
});
");

?>
<h1>Senders</h1>
<?php 

if (Yii::app()->user->hasFlash('trained')) {
  $this->widget('bootstrap.widgets.TbAlert', array(
      'block'=>true, // display a larger alert block?
      'fade'=>true, // use transitions?
      'closeText'=>'×', // close link text - if set to false, no close link is displayed
      'alerts'=>array( // configurations per alert type
  	    'trained'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), // success, info, warning, error or danger
      ),
  ));
  
}

?>

<div>
  <div class="right">
    </div>
  <div class="left;">
  <?php
  $this->widget('bootstrap.widgets.TbButtonGroup', array(
    'type' => 'success',
        'toggle' => 'radio',
            'buttons'=>array(
                array('label'=>'Untrained', 'url'=>Yii::app()->getBaseUrl(true).'/sender/index'),
                array('label'=>'Trained', 'url'=>Yii::app()->getBaseUrl(true).'/sender/trained'),
                array('label'=>'Recent', 'url'=>Yii::app()->getBaseUrl(true).'/sender/recent','htmlOptions'=> array('class'=>'active')),
      ),
  ));
  ?>
</div>
</div>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'sender-form',
	'enableAjaxValidation'=>false,
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'sender-grid',
	'dataProvider'=>$model->recent()->search(),
	'filter'=>$model,
	'columns'=>array(
    array('class'=>'CCheckBoxColumn','selectableRows'=>2),	  
		'personal',
		'email',
  	array('class'=>'CDataColumn','name'=> 'message_count', 'header'=>'# Msgs'),
  array(            
            'name'=>'folder_name',
            'header'=>'Folder',
            'filter'=>CHtml::dropDownList(
                                            'Sender[folder_name]',
                                            $model->folder_name,
                                            CHtml::listData(
                                                    Folder::model()->findAll(),
                                                    'name',
                                                    'name'),array('empty' => 'All')),
            'value'=>'$data->folder_name',
        ),
    array(            
                'name'=>'account_name',
                'header'=>'Account',
                'filter'=>CHtml::dropDownList(
                                                'Sender[account_name]',
                                                $model->account_name,
                                                CHtml::listData(
                                                        Account::model()->findAll(),
                                                        'name',
                                                        'name'),array('empty' => 'All')),                
                'value'=>'$data->account_name',
            ),
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
    	'header'=>'Options',
      'template'=>'{update}{delete}',
		),
	),
)); ?>
<div class="form-actions">

<?php 
    echo CHtml::activeLabel($model,'folder_id',array('label'=>'Train to Folder:')); 
    echo CHtml::activeDropDownList($model,'folder_id',Sender::model()->getFolderOptions(),array('empty'=>'Select a Folder'));
    echo '<br />';
   $this->widget('bootstrap.widgets.TbButton', array(
	'buttonType'=>'submit',
	'type'=>'primary',
	'label'=>'Save',
)); ?>

</div>
<?php $this->endWidget(); ?>

app/protected/views/sender/trained.php
<?php
$this->breadcrumbs=array(
	'Senders',
);
$this->menu=array(
//	array('label'=>'Create Sender','url'=>array('create')),
 array('label'=>'Manage Sender','url'=>array('admin')),
);
Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('sender-grid', {
		data: $(this).serialize()
	});
	return false;
});
");

?>
<h1>Senders</h1>
<?php 

if (Yii::app()->user->hasFlash('trained')) {
  $this->widget('bootstrap.widgets.TbAlert', array(
      'block'=>true, // display a larger alert block?
      'fade'=>true, // use transitions?
      'closeText'=>'×', // close link text - if set to false, no close link is displayed
      'alerts'=>array( // configurations per alert type
  	    'trained'=>array('block'=>true, 'fade'=>true, 'closeText'=>'×'), // success, info, warning, error or danger
      ),
  ));
  
}

?>

<div>
  <div class="right">
    </div>
  <div class="left;">
  <?php
  $this->widget('bootstrap.widgets.TbButtonGroup', array(
    'type' => 'success',
        'toggle' => 'radio',
            'buttons'=>array(
                array('label'=>'Untrained', 'url'=>Yii::app()->getBaseUrl(true).'/sender/index'),
                array('label'=>'Trained', 'url'=>Yii::app()->getBaseUrl(true).'/sender/trained','htmlOptions'=> array('class'=>'active')),
                array('label'=>'Recent', 'url'=>Yii::app()->getBaseUrl(true).'/sender/recent'),            
      ),
  ));
  ?>
</div>
</div>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'sender-form',
	'enableAjaxValidation'=>false,
)); ?>

<?php 
$this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'sender-grid',
	'dataProvider'=>$model->trained()->search(),
	'filter'=>$model,
	'columns'=>array(
    array('class'=>'CCheckBoxColumn','selectableRows'=>2),	  
		'personal',
		'email',
  	array('class'=>'CDataColumn','name'=> 'message_count', 'header'=>'# Msgs'),
    array(            
                'name'=>'folder_name',
                'header'=>'Folder',
                'filter'=>CHtml::dropDownList(
                                                'Sender[folder_name]',
                                                $model->folder_name,
                                                CHtml::listData(
                                                        Folder::model()->findAll(),
                                                        'name',
                                                        'name'),array('empty' => 'All')),
                'value'=>'$data->folder_name',
            ),
    array(            
                'name'=>'account_name',
                'header'=>'Account',
                'filter'=>CHtml::dropDownList(
                                                'Sender[account_name]',
                                                $model->account_name,
                                                CHtml::listData(
                                                        Account::model()->findAll(),
                                                        'name',
                                                        'name'),array('empty' => 'All')),                
                'value'=>'$data->account_name',
            ),
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
    	'header'=>'Options',
      'template'=>'{update}{delete}',
		),
	),
)); ?>
<div class="form-actions">

<?php 
    echo CHtml::activeLabel($model,'folder_id',array('label'=>'Train to Folder:')); 
    echo CHtml::activeDropDownList($model,'folder_id',Sender::model()->getFolderOptions(),array('empty'=>'Select a Folder'));
    echo '<br />';
   $this->widget('bootstrap.widgets.TbButton', array(
	'buttonType'=>'submit',
	'type'=>'primary',
	'label'=>'Save',
)); ?>

</div>
<?php $this->endWidget(); ?>